/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymgmt;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sravani
 */
public class panelAuthors extends javax.swing.JPanel {

    /**
     * Creates new form panelAuthors
     */
    static boolean close = false;
    public panelAuthors() {
        initComponents();
        setTableData();
        btnAuthorAdd.setEnabled(false);
        btnAuthorUpdate.setEnabled(true);
        btnAuthorDelete.setEnabled(true);
    }
    
    public void setTableData()
    {
        DefaultTableModel dtm = new DefaultTableModel(0, 0);  
        String s[] = new String[]{"Author ID", "Author Name"};  
        dtm.setColumnIdentifiers(s);  
        tableAuthor.setModel(dtm); 
    }
    
     public void getTableData() {  
           
           DefaultTableModel dtm = new DefaultTableModel(0, 0);  
            String s[] = new String[]{"Author ID", "Author Name"};  
            dtm.setColumnIdentifiers(s);  
            tableAuthor.setModel(dtm); 
            
          try {  
                Utilities.registerDriver();
                Connection con;
                con = Utilities.getSqlConnection();  
                ResultSet rs = null; 
                String sql = "Select author_id, author_name from authors where author_name like '%" + txtAuthorSearch.getText() + "%';";
                System.out.println(sql);
                rs = Utilities.getResultSet(con,sql);
                while (rs.next()) 
                {  
                    String authorId = rs.getString(1);
                    String authorName = rs.getString(2);
                    Vector<String> vector = new Vector<String>();  
                    vector.add(authorId);  
                    vector.add(authorName);

                    dtm.addRow(vector);  
                }  
        } 
        catch (SQLException ex) 
        {  
          //Logger.getLogger(JdefaluttableDemo.class.getName()).log(Level.SEVERE, null, ex);  
        }  
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAuthorId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtAuthorName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tbtnNewAuthor = new javax.swing.JToggleButton();
        btnAuthorAdd = new javax.swing.JButton();
        btnAuthorUpdate = new javax.swing.JButton();
        btnAuthorDelete = new javax.swing.JButton();
        btnAuthorClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAuthor = new javax.swing.JTable();
        txtAuthorSearch = new javax.swing.JTextField();
        btnAuthorSearch = new javax.swing.JButton();

        txtAuthorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAuthorIdActionPerformed(evt);
            }
        });

        jLabel1.setText("Id :");

        jLabel2.setText("Name:");

        tbtnNewAuthor.setText("New Author");
        tbtnNewAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnNewAuthorActionPerformed(evt);
            }
        });

        btnAuthorAdd.setText("Add");
        btnAuthorAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthorAddActionPerformed(evt);
            }
        });

        btnAuthorUpdate.setText("Update");
        btnAuthorUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthorUpdateActionPerformed(evt);
            }
        });

        btnAuthorDelete.setText("Delete");
        btnAuthorDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthorDeleteActionPerformed(evt);
            }
        });

        btnAuthorClose.setText("Close");
        btnAuthorClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthorCloseActionPerformed(evt);
            }
        });

        tableAuthor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableAuthor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAuthorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAuthor);

        btnAuthorSearch.setText("Search");
        btnAuthorSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthorSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel2)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAuthorName)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAuthorId, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnAuthorAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnAuthorUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnAuthorDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnAuthorClose, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(txtAuthorSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(tbtnNewAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAuthorSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAuthorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(tbtnNewAuthor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAuthorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAuthorAdd)
                    .addComponent(btnAuthorUpdate)
                    .addComponent(btnAuthorDelete)
                    .addComponent(btnAuthorClose))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAuthorSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAuthorSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAuthorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAuthorIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAuthorIdActionPerformed

    private void tbtnNewAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnNewAuthorActionPerformed
        // TODO add your handling code here:
         if(tbtnNewAuthor.isSelected())
        {
            btnAuthorUpdate.setEnabled(false);
            btnAuthorDelete.setEnabled(false);
            btnAuthorAdd.setEnabled(true);
        }
        else
        {
            btnAuthorAdd.setEnabled(false);
            btnAuthorUpdate.setEnabled(true);
            btnAuthorDelete.setEnabled(true);
        }
    }//GEN-LAST:event_tbtnNewAuthorActionPerformed

    private void btnAuthorAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthorAddActionPerformed
        // TODO add your handling code here:
        try
        {
            Utilities.registerDriver();
            Connection con;
            con = Utilities.getSqlConnection();  
            ResultSet rs = null; 
            String sql = "Insert into authors values (" + txtAuthorId.getText() + ", '" + txtAuthorName.getText() + "');";
            System.out.println(sql);
            rs = Utilities.getResultSet(con,sql);
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_btnAuthorAddActionPerformed

    private void btnAuthorSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthorSearchActionPerformed
        // TODO add your handling code here:
        getTableData();
    }//GEN-LAST:event_btnAuthorSearchActionPerformed

    private void btnAuthorUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthorUpdateActionPerformed
        // TODO add your handling code here:
         try
        {
            Utilities.registerDriver();
            Connection con;
            con = Utilities.getSqlConnection();  
            ResultSet rs = null; 
            String sql = "Update authors set author_name = '" + txtAuthorName.getText() + "' where author_id = " + txtAuthorId.getText() + ";";
            System.out.println(sql);
            rs = Utilities.getResultSet(con,sql);
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_btnAuthorUpdateActionPerformed

    private void btnAuthorCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthorCloseActionPerformed
        // TODO add your handling code here:
        close = true;
        if(close == true)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnAuthorCloseActionPerformed

    private void tableAuthorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAuthorMouseClicked
        // TODO add your handling code here:
        try
        {
            int row = tableAuthor.getSelectedRow();
            String Table_click = (tableAuthor.getModel().getValueAt(row,0).toString());
            String sql = "select * from authors where author_id = " + Table_click + ";";
            Utilities.registerDriver();
            Connection con;
            con = Utilities.getSqlConnection();  
            ResultSet rs = null;
            System.out.println(sql);
            rs = Utilities.getResultSet(con,sql);
            if(rs.next())
            {
                String add1 = rs.getString("author_id");
                txtAuthorId.setText(add1);
                String add2 = rs.getString("author_name");
                txtAuthorName.setText(add2);
            
            }
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_tableAuthorMouseClicked

    private void btnAuthorDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthorDeleteActionPerformed
        // TODO add your handling code here:
        Utilities.registerDriver();
        Connection con;
        con = Utilities.getSqlConnection();
        ResultSet rs = null;
        ResultSet rs1 = null;
        ResultSet rs3 = null;
        String sql = "";
        String sql1 = "";
        String sql3 = "";
        sql3 = "Delete from issuedbooks where isbn in (select isbn from books where author_id = " + txtAuthorId.getText() + ");";
        sql = "Delete from books where author_id = " + txtAuthorId.getText() + ";";
        sql1 = "Delete from authors where author_id = " + txtAuthorId.getText() + ";";
        System.out.println(sql);
        System.out.println(sql1);
        rs3 = Utilities.getResultSet(con,sql3);
        rs = Utilities.getResultSet(con,sql);
        rs1 = Utilities.getResultSet(con,sql1);
    }//GEN-LAST:event_btnAuthorDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuthorAdd;
    private javax.swing.JButton btnAuthorClose;
    private javax.swing.JButton btnAuthorDelete;
    private javax.swing.JButton btnAuthorSearch;
    private javax.swing.JButton btnAuthorUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAuthor;
    private javax.swing.JToggleButton tbtnNewAuthor;
    private javax.swing.JTextField txtAuthorId;
    private javax.swing.JTextField txtAuthorName;
    private javax.swing.JTextField txtAuthorSearch;
    // End of variables declaration//GEN-END:variables
}
