/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymgmt;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import static librarymgmt.panelAuthors.close;

/**
 *
 * @author sravani
 */
public class panelPublishers extends javax.swing.JPanel {

    /**
     * Creates new form panelPublishers
     */
    public panelPublishers() {
        initComponents();
        setTableData();
        btnPublisherAdd.setEnabled(false);
        btnPublisherUpdate.setEnabled(true);
        btnPublisherDelete.setEnabled(true);
    }
    
    public void setTableData()
    {
        DefaultTableModel dtm = new DefaultTableModel(0, 0);  
        String s[] = new String[]{"Publisher ID", "Publisher Name"};  
        dtm.setColumnIdentifiers(s);  
        tablePublisher.setModel(dtm); 
    }
    
     public void getTableData() {  
           
           DefaultTableModel dtm = new DefaultTableModel(0, 0);  
            String s[] = new String[]{"Publisher ID", "Publisher Name"};  
            dtm.setColumnIdentifiers(s);  
            tablePublisher.setModel(dtm); 
            
          try {  
                Utilities.registerDriver();
                Connection con;
                con = Utilities.getSqlConnection();  
                ResultSet rs = null; 
                String sql = "Select publisher_id, publisher_name from publishers where publisher_name like '%" + txtPublisherSearch.getText() + "%';";
                System.out.println(sql);
                rs = Utilities.getResultSet(con,sql);
                while (rs.next()) 
                {  
                    String publisherId = rs.getString(1);
                    String publisherName = rs.getString(2);
                    Vector<String> vector = new Vector<String>();  
                    vector.add(publisherId);  
                    vector.add(publisherName);

                    dtm.addRow(vector);  
                }  
        }
        catch (SQLException ex) 
        {  
          //Logger.getLogger(JdefaluttableDemo.class.getName()).log(Level.SEVERE, null, ex);  
        }  
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPublisherId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPublisherName = new javax.swing.JTextField();
        btnPublisherAdd = new javax.swing.JButton();
        btnPublisherUpdate = new javax.swing.JButton();
        btnPublisherDelete = new javax.swing.JButton();
        btnPublisherSearch = new javax.swing.JButton();
        btnPublisherClose = new javax.swing.JButton();
        txtPublisherSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePublisher = new javax.swing.JTable();
        tbtnNewPublisher = new javax.swing.JToggleButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Id :");

        jLabel2.setText("Publisher Name :");

        btnPublisherAdd.setText("Add");
        btnPublisherAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublisherAddActionPerformed(evt);
            }
        });

        btnPublisherUpdate.setText("Update");
        btnPublisherUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublisherUpdateActionPerformed(evt);
            }
        });

        btnPublisherDelete.setText("Delete");
        btnPublisherDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublisherDeleteActionPerformed(evt);
            }
        });

        btnPublisherSearch.setText("Search");
        btnPublisherSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublisherSearchActionPerformed(evt);
            }
        });

        btnPublisherClose.setText("Close");
        btnPublisherClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublisherCloseActionPerformed(evt);
            }
        });

        tablePublisher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePublisher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePublisherMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePublisher);

        tbtnNewPublisher.setText("New Publisher");
        tbtnNewPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnNewPublisherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPublisherSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtPublisherId, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(135, 135, 135)
                                        .addComponent(tbtnNewPublisher))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnPublisherAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPublisherUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPublisherDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPublisherClose))
                                    .addComponent(txtPublisherName, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(248, 248, 248)
                                    .addComponent(btnPublisherSearch))))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPublisherId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbtnNewPublisher))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPublisherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPublisherClose)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPublisherAdd)
                        .addComponent(btnPublisherUpdate)
                        .addComponent(btnPublisherDelete)))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPublisherSearch)
                    .addComponent(txtPublisherSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 420, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPublisherSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublisherSearchActionPerformed
        // TODO add your handling code here:
        getTableData();
    }//GEN-LAST:event_btnPublisherSearchActionPerformed

    private void tbtnNewPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnNewPublisherActionPerformed
        // TODO add your handling code here:
        if(tbtnNewPublisher.isSelected())
        {
            btnPublisherUpdate.setEnabled(false);
            btnPublisherDelete.setEnabled(false);
            btnPublisherAdd.setEnabled(true);
        }
        else
        {
            btnPublisherAdd.setEnabled(false);
            btnPublisherUpdate.setEnabled(true);
            btnPublisherDelete.setEnabled(true);
        }
    }//GEN-LAST:event_tbtnNewPublisherActionPerformed

    private void btnPublisherAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublisherAddActionPerformed
        // TODO add your handling code here:
        try
        {
            Utilities.registerDriver();
            Connection con;
            con = Utilities.getSqlConnection();  
            ResultSet rs = null; 
            String sql = "Insert into publishers values (" + txtPublisherId.getText() + ", '" + txtPublisherName.getText() + "');";
            System.out.println(sql);
            rs = Utilities.getResultSet(con,sql);
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_btnPublisherAddActionPerformed

    private void btnPublisherUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublisherUpdateActionPerformed
        // TODO add your handling code here:
        try
        {
            Utilities.registerDriver();
            Connection con;
            con = Utilities.getSqlConnection();  
            ResultSet rs = null; 
            String sql = "Update publishers set publisher_name = '" + txtPublisherName.getText() + "' where publisher_id = " + txtPublisherId.getText() + ";";
            System.out.println(sql);
            rs = Utilities.getResultSet(con,sql);
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_btnPublisherUpdateActionPerformed

    private void btnPublisherDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublisherDeleteActionPerformed
        // TODO add your handling code here:
        Utilities.registerDriver();
        Connection con;
        con = Utilities.getSqlConnection();
        ResultSet rs = null;
        ResultSet rs1 = null;
        ResultSet rs3 = null;
        String sql = "";
        String sql1 = "";
        String sql3 = "";
        sql3 = "Delete from issuedbooks where isbn in (select isbn from books where publisher_id = " + txtPublisherId.getText() + ");";
        sql = "Delete from books where publisher_id = " + txtPublisherId.getText() + ";";
        sql1 = "Delete from publishers where publisher_id = " + txtPublisherId.getText() + ";";
        System.out.println(sql3);
        System.out.println(sql);
        System.out.println(sql1);
        rs3 = Utilities.getResultSet(con,sql3);
        rs = Utilities.getResultSet(con,sql);
        rs1 = Utilities.getResultSet(con,sql1);
    }//GEN-LAST:event_btnPublisherDeleteActionPerformed

    private void tablePublisherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePublisherMouseClicked
        // TODO add your handling code here:
        try
        {
            int row = tablePublisher.getSelectedRow();
            String Table_click = (tablePublisher.getModel().getValueAt(row,0).toString());
            String sql = "select * from publishers where publisher_id = " + Table_click + ";";
            Utilities.registerDriver();
            Connection con;
            con = Utilities.getSqlConnection();  
            ResultSet rs = null;
            System.out.println(sql);
            rs = Utilities.getResultSet(con,sql);
            if(rs.next())
            {
                String add1 = rs.getString("publisher_id");
                txtPublisherId.setText(add1);
                String add2 = rs.getString("publisher_name");
                txtPublisherName.setText(add2);
            
            }
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_tablePublisherMouseClicked

    private void btnPublisherCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublisherCloseActionPerformed
        // TODO add your handling code here:
        close = true;
        if(close == true)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnPublisherCloseActionPerformed
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPublisherAdd;
    private javax.swing.JButton btnPublisherClose;
    private javax.swing.JButton btnPublisherDelete;
    private javax.swing.JButton btnPublisherSearch;
    private javax.swing.JButton btnPublisherUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePublisher;
    private javax.swing.JToggleButton tbtnNewPublisher;
    private javax.swing.JTextField txtPublisherId;
    private javax.swing.JTextField txtPublisherName;
    private javax.swing.JTextField txtPublisherSearch;
    // End of variables declaration//GEN-END:variables
}
