/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymgmt;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sravani
 */
public class panelStudents extends javax.swing.JPanel {

    /**
     * Creates new form panelStudents
     */
    public panelStudents() {
        initComponents();
        setTableData();
        btnStudentAdd.setEnabled(false);
        btnStudentUpdate.setEnabled(true);
        btnStudentDelete.setEnabled(true);
    }
    
    public void setTableData()
    {
        DefaultTableModel dtm = new DefaultTableModel(0, 0);  
        String s[] = new String[]{"Student ID", "User Name", "First Name", "Last Name", "Password", "email", "phone_no"};  
        dtm.setColumnIdentifiers(s);  
        tableStudent.setModel(dtm);
    }
    
    public void getTableData() {  
           
           DefaultTableModel dtm = new DefaultTableModel(0, 0);  
            String s[] = new String[]{"Student ID", "User Name", "First Name", "Last Name", "Password", "email", "phone_no"};  
            dtm.setColumnIdentifiers(s);  
            tableStudent.setModel(dtm); 
            
          try {  
                Utilities.registerDriver();
                Connection con;
                con = Utilities.getSqlConnection();  
                ResultSet rs = null; 
                String comboSelect = comboBoxStudents.getSelectedItem().toString();
                String sql = "";
                if(comboSelect.equals("User Name"))
                {
                    sql = "Select * from users where user_name like '%" + txtStudentSearch.getText() + "%';";
                }
                else if(comboSelect.equals("First Name"))
                {
                    sql = "Select * from users where first_name like '%" + txtStudentSearch.getText() + "%';";
                }
                else if(comboSelect.equals("Last Name"))
                {
                    sql = "Select * from users where last_name like '%" + txtStudentSearch.getText() + "%';";
                }
                else if(comboSelect.equals("Phone No"))
                {
                    sql = "Select * from users where phone_no = " + txtStudentSearch.getText() + ";";
                }
                System.out.println(sql);
                rs = Utilities.getResultSet(con,sql);
                while (rs.next()) 
                {  
                    String studentId = rs.getString(1);
                    String userName = rs.getString(2);
                    String firstName = rs.getString(3);
                    String lastName = rs.getString(4);
                    String password = rs.getString(5);
                    String email = rs.getString(6);
                    String phoneNo = rs.getString(7);
                    Vector<String> vector = new Vector<String>();  
                    vector.add(studentId);  
                    vector.add(userName);  
                    vector.add(firstName);
                    vector.add(lastName);  
                    vector.add(password);
                    vector.add(email);
                    vector.add(phoneNo);  

                    dtm.addRow(vector);  
                }  
        } 
        catch (SQLException ex) 
        {  
          //Logger.getLogger(JdefaluttableDemo.class.getName()).log(Level.SEVERE, null, ex);  
        }  
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtStudenUsertId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtStudentUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtStudentFirstName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtStudentLastName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        passStudentPassword = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtStudentEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        numStudentPhnNum = new javax.swing.JTextField();
        btnStudentAdd = new javax.swing.JButton();
        btnStudentUpdate = new javax.swing.JButton();
        btnStudentDelete = new javax.swing.JButton();
        btnStudentClose = new javax.swing.JButton();
        btnStudentSearch = new javax.swing.JButton();
        txtStudentSearch = new javax.swing.JTextField();
        comboBoxStudents = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableStudent = new javax.swing.JTable();
        tbtnNewStudent = new javax.swing.JToggleButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("User Id :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 29, -1, -1));
        add(txtStudenUsertId, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 26, 300, -1));

        jLabel2.setText("User Name :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 57, -1, -1));
        add(txtStudentUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 54, 300, -1));

        jLabel3.setText("First Name :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 83, -1, -1));
        add(txtStudentFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 80, 300, -1));

        jLabel4.setText("Last Name :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 109, -1, -1));
        add(txtStudentLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 106, 300, -1));

        jLabel5.setText("Password :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 135, -1, -1));
        add(passStudentPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 132, 300, -1));

        jLabel6.setText("e-Mail :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 161, -1, -1));
        add(txtStudentEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 158, 300, -1));

        jLabel7.setText("Phone No :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 187, -1, -1));
        add(numStudentPhnNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 184, 300, -1));

        btnStudentAdd.setText("Add");
        btnStudentAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentAddActionPerformed(evt);
            }
        });
        add(btnStudentAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 100, -1));

        btnStudentUpdate.setText("Update");
        add(btnStudentUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 90, -1));

        btnStudentDelete.setText("Delete");
        add(btnStudentDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 90, -1));

        btnStudentClose.setText("Close");
        add(btnStudentClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 100, -1));

        btnStudentSearch.setText("Search");
        btnStudentSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentSearchActionPerformed(evt);
            }
        });
        add(btnStudentSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 100, -1));
        add(txtStudentSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 190, -1));

        comboBoxStudents.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User Name", "First Name", "Last Name", "Phone No" }));
        comboBoxStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxStudentsActionPerformed(evt);
            }
        });
        add(comboBoxStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 100, -1));

        tableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableStudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableStudent);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 590, 130));

        tbtnNewStudent.setText("New Student");
        tbtnNewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnNewStudentActionPerformed(evt);
            }
        });
        add(tbtnNewStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 20, 110, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentSearchActionPerformed
        // TODO add your handling code here:
       getTableData(); 
    }//GEN-LAST:event_btnStudentSearchActionPerformed

    private void btnStudentAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentAddActionPerformed
        // TODO add your handling code here:
        try
        {
            Utilities.registerDriver();
            Connection con;
            con = Utilities.getSqlConnection();  
            ResultSet rs = null; 
            String sql = "Insert into users values (" + txtStudenUsertId.getText() + ", '" + txtStudentUserName.getText() + "','" + txtStudentFirstName.getText() + "','" + txtStudentLastName.getText() + "','" + passStudentPassword.getText() + "','" + txtStudentEmail.getText() + "'," + numStudentPhnNum.getText() + ");";;
            System.out.println(sql);
            rs = Utilities.getResultSet(con,sql);
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_btnStudentAddActionPerformed

    private void tbtnNewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnNewStudentActionPerformed
        // TODO add your handling code here:
        if(tbtnNewStudent.isSelected())
        {
            btnStudentUpdate.setEnabled(false);
            btnStudentDelete.setEnabled(false);
            btnStudentAdd.setEnabled(true);
        }
        else
        {
            btnStudentAdd.setEnabled(false);
            btnStudentUpdate.setEnabled(true);
            btnStudentDelete.setEnabled(true);
        }
    }//GEN-LAST:event_tbtnNewStudentActionPerformed

    private void comboBoxStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxStudentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxStudentsActionPerformed

    private void tableStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableStudentMouseClicked
        // TODO add your handling code here:
        try
        {
            int row = tableStudent.getSelectedRow();
            String Table_click = (tableStudent.getModel().getValueAt(row,0).toString());
            String sql = "select * from users where user_id = " + Table_click + ";";
            Utilities.registerDriver();
            Connection con;
            con = Utilities.getSqlConnection();  
            ResultSet rs = null;
            System.out.println(sql);
            rs = Utilities.getResultSet(con,sql);
            if(rs.next())
            {
                String add1 = rs.getString("user_id");
                txtStudenUsertId.setText(add1);
                String add2 = rs.getString("user_name");
                txtStudentUserName.setText(add2);
                String add3 = rs.getString("first_name");
                txtStudentFirstName.setText(add3);
                String add4 = rs.getString("last_name");
                txtStudentLastName.setText(add4);
                String add5 = rs.getString("password");
                passStudentPassword.setText(add5);
                String add6 = rs.getString("email");
                txtStudentEmail.setText(add6);
                String add7 = rs.getString("phone_no");
                numStudentPhnNum.setText(add7);
            }
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_tableStudentMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStudentAdd;
    private javax.swing.JButton btnStudentClose;
    private javax.swing.JButton btnStudentDelete;
    private javax.swing.JButton btnStudentSearch;
    private javax.swing.JButton btnStudentUpdate;
    private javax.swing.JComboBox<String> comboBoxStudents;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numStudentPhnNum;
    private javax.swing.JTextField passStudentPassword;
    private javax.swing.JTable tableStudent;
    private javax.swing.JToggleButton tbtnNewStudent;
    private javax.swing.JTextField txtStudenUsertId;
    private javax.swing.JTextField txtStudentEmail;
    private javax.swing.JTextField txtStudentFirstName;
    private javax.swing.JTextField txtStudentLastName;
    private javax.swing.JTextField txtStudentSearch;
    private javax.swing.JTextField txtStudentUserName;
    // End of variables declaration//GEN-END:variables
}
