/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymgmt;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sravani
 */
public class panelBooksTakenHistory extends javax.swing.JPanel {

    /**
     * Creates new form panelBooksTakenHistory
     */
    public panelBooksTakenHistory() {
        initComponents();
        getTableData();
    }

    
     public void getTableData() {  
           
           DefaultTableModel dtm = new DefaultTableModel(0, 0);  
            String s[] = new String[]{"ISBN", "Book Name", "Fine", "Issue Date", "Return Date"};  
            dtm.setColumnIdentifiers(s);  
            tableBooksTaken.setModel(dtm); 
            
          try {  
                Utilities.registerDriver();
                Connection con;
                con = Utilities.getSqlConnection();  
                ResultSet rs = null; 
                String sql = "select issuedbooks.isbn,title,fine,issued_date,return_date from issuedbooks inner join books on books.isbn = issuedbooks.isbn inner join users on issuedbooks.user_id = users.user_id  where user_name = '" + AppValues.selectedUserName + "';";
                System.out.println(sql);
                rs = Utilities.getResultSet(con,sql);
                while (rs.next()) 
                {  
                    String isbn = rs.getString(1);
                    String title = rs.getString(2);
                    String fine = rs.getString(3);
                    String issuedDate = rs.getString(4);
                    String returnDate = rs.getString(5);
                    Vector<String> vector = new Vector<String>();  
                    vector.add(isbn);  
                    vector.add(title);  
                    vector.add(fine);
                    vector.add(issuedDate);  
                    vector.add(returnDate); 

                    dtm.addRow(vector);  
                }  
        } 
        catch (Exception ex) 
        {   
            
        }  
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableBooksTaken = new javax.swing.JTable();

        tableBooksTaken.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableBooksTaken);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableBooksTaken;
    // End of variables declaration//GEN-END:variables
}
